# TAP results for test_pdb_on_fail.py
not ok 1 - test_pdb_on_fail.py::test_func
# 
#     def test_func():
# >       assert 0
# E       assert 0
# 
# test_pdb_on_fail.py:2: AssertionError
1..1
